### ISSUE TITLE
Spreading Rot Jewel Outdated

### ISSUE THREAD

**Issue by HyperWeapon** [LocalIdentity/PathOfBuilding#155]
Spreading Rot was changed in 3.6. This was never updated in PoB. 
https://pathofexile.gamepedia.com/Spreading_Rot#Version_history
Here's a comparison image.
![image](https://user-images.githubusercontent.com/16571440/73990641-fe1a7680-4906-11ea-81ab-de77c8d0b28f.png)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.157.2

**Comment by TechTrooper** [comment]
This jewel doesn't seem to work properly. 

I've tried applying 0 and 15 stacks of withered in options, but it still does nothing to DPS without also adding Wither skill gem.
